### ISSUE TITLE
make the time slider look "more like a time slider"

### ISSUE THREAD

**Issue by ryales** [SimonbJohnson/europe-15-situational-awareness#27]
Henk requests the time slider get a facelift. It needs to look more obviously like a time slider that people can play with. Will require webkit css.

HTML5 Styling:
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
- http://brennaobrien.com/blog/2014/05/style-input-type-range-in-every-browser.html

**Comment by SimonbJohnson** [comment]
@ryales - currently it is using the new standard html5 input range.  I think some of the above may be using code from before it existed.  Could be worth seeing what the latest method is and see if the html5 native one can be adapted.
